version: '3.8'

services:
  trazabilidad:
    build: ./trazabilidad
    container_name: citypass_trazabilidad
    restart: unless-stopped
    environment:
      - RABBITMQ_HOST=172.31.19.186
      - PGHOST=172.31.19.186
      - PGPORT=5432
      - PGDATABASE=citypass_logs
      - PGUSER=citypass
      - PGPASSWORD=citypass
    networks:
      - citypass_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  back:
    build: ./back
    container_name: citypass_back
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - RABBITMQ_HOST=172.31.19.186
      - PGHOST=172.31.19.186
      - PGPORT=5432
      - PGDATABASE=citypass_logs
      - PGUSER=citypass
      - PGPASSWORD=citypass
    networks:
      - citypass_network
    depends_on:
      - trazabilidad
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  front:
    build: ./front
    container_name: citypass_front
    restart: unless-stopped
    ports:
      - "5500:80"
    environment:
      - VITE_BACKEND_URL=http://citypass_back:5000
    networks:
      - citypass_network
    depends_on:
      - back
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  citypass_network:
    driver: bridge
